[train]
n = 5
frac_train = 0.4
batch_size = 16384
num_epochs = 500000
grok_threshold = 0.00001
checkpoint_every = 1000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512]
device = 'cuda'
seed = 314159

[model]
embed_dim = 256
model_dim = 128
vocab_size = 120
tie_left_right = false


[optimizer]
lr = 1e-3
wd = 1.0
betas = [0.9, 0.98]


[wandb]
entity= 'dstander'
project = 'grokking_sn'
group = 'A5_basic'

