[train]
n = 6 
frac_train = 0.50
batch_size = 16384
num_epochs = 200000
grok_threshold = 0.00001
checkpoint_every = 10000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512, 1024, 2048, 4096, 8192]
device = "cuda"
seed = 128
checkpoint_dir = "checkpoints"
run_dir = "a6_50"


[group]
@groups = "groups.An"
n = ${train.n}

[model]
embed_dim = 1024
model_dim = 256
vocab_size = 360
tie_lr = false


[optimizer]
algorithm = "adam"
lr = 1e-3
weight_decay = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "A6_50pcnt"
project = "grokking_sn"
