[train]
n = 5
frac_train = 0.5
seed = 0
batch_size = 16384
num_epochs = 250000
checkpoint_every = 10000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
device = "cuda"
checkpoint_dir = "checkpoints/"
run_dir = "s5_50_gelu"


[group]
@groups = "Sn"
n = 5


[model]
embed_dim = 256
model_dim = 128
vocab_size = 120
act_fn = "gelu"
tie_lr = false


[optimizer]
algorithm = "adam"
lr = 1e-3
weight_decay = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S5_50pcnt_gelu"
project = "grokking_sn"
