[train]
n = 5
frac_train = 0.5
batch_size = 16384
num_epochs = 250000
grok_threshold = 0.00001
checkpoint_every = 2000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512, 1024]
device = "cuda"


[group]
@groups = "Sn"
n = ${train.n}


[model]
embed_dim = 256
model_dim = 128
vocab_size = 120
tie_lr = false


[optimizer]
lr = 1e-3
wd = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S5_50pcnt_experiment"
project = "grokking_sn"
