[train]
n = 5
frac_train = 0.4
batch_size = 16384
num_epochs = 500000
parity = "all"
grok_threshold = 0.00001
checkpoint_every = 1000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512]
device = "cuda"
seed = 16
checkpoint_dir = "checkpoints"
run_dir = "s5_ft_40"

[model]
embed_dim = 256
model_dim = 128
vocab_size = 120
tie_lr = false


[pretrained_model]
embed_dim = 256
model_dim = 128
vocab_size = 120
tie_lr = false
checkpoint_path = "checkpoints/a5_40/"


[optimizer]
lr = 1e-3
wd = 1.0
betas = [0.9, 0.98]


[wandb]
entity= "dstander"
project = "grokking_sn"
group = "S5_40pcnt_finetune"
