[train]
n = 5
frac_train = 0.50
batch_size = 16384
num_epochs = 2000000
grok_threshold = 0.00001
checkpoint_every = 50000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512, 1024, 2048, 4096, 8192, 16384, 32768]
device = "cuda"
seed = 5 
checkpoint_dir = "checkpoints"
run_dir = "s5_lr1e-5"

[group]
@groups = "Sn"
n = ${train.n}


[model]
embed_dim = 256
model_dim = 128
vocab_size = 120
tie_lr = false


[optimizer]
lr = 1e-5
wd = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S5_lr1e-5"
project = "grokking_sn"
