[train]
n = 5
frac_train = 0.4
batch_size = 16384
num_epochs = 250000
checkpoint_every = 10000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512, 1024, 2048, 4096, 8192]
device = "cuda"
checkpoint_dir = "/mnt/ssd-1/sn-circuits/transformer"
run_dir = "s5_40"
seed = 0


[group]
@groups = "Sn"
n = 5


[model]
d_model = 256
d_head = 64
n_heads = 4
d_mlp = 1024
n_ctx = 3
n_layers = 1
d_vocab = 121
d_vocab_out = 120
act_fn = "relu"
use_ln = false

[optimizer]
algorithm = "adam"
lr = 1e-3
weight_decay = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S5_40"
project = "sn_transformer"
