[train]
n = 6 
frac_train = 0.4
batch_size = 16384
num_epochs = 50000
checkpoint_every = 1000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512]
device = "cuda"
checkpoint_dir = "/mnt/ssd-1/sn-circuits/S6_sweep"
run_dir = "s6_40"


[group]
@groups = "Sn"
n = ${train.n}

[model]
embed_dim = 512
model_dim = 256
vocab_size = 720
tie_lr = false


[optimizer]
algorithm = "adam"
lr = 1e-3
weight_decay = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S6_40pcnt_sweep"
project = "S6_40pcnt"
