[train]
n = 6 
frac_train = 0.50
batch_size = 16384
num_epochs = 200000
parity = "all"
grok_threshold = 0.00001
checkpoint_every = 10000
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 512, 1024, 2048, 4096, 8192]
device = "cuda"
seed = 128
checkpoint_dir = "checkpoints"
run_dir = "s6_50"

[model]
embed_dim = 512
model_dim = 256
vocab_size = 720
tie_lr = false


[optimizer]
lr = 1e-3
wd = 1.0
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S6_50pcnt_sweep"
project = "grokking_sn"
