[train]
n = 7
frac_train = 0.95
batch_size = 131072
num_epochs = 1000
checkpoint_every = 50
extra_checkpoints = [2, 4, 8, 16, 32, 64, 128, 256, 512]
device = "cuda"
checkpoint_dir = "checkpoints/S7_init"
run_dir = "s7_95"
seed = 0


[group]
@groups = "Sn"
n = ${train.n}

[model]
embed_dim = 1024
model_dim = 8192
vocab_size = 5040
tie_lr = false


[optimizer]
algorithm = "adam"
lr = 1e-3
weight_decay = 0.2
betas = [0.9, 0.98]


[wandb]
entity = "dstander"
group = "S7_95pcnt_sweep"
project = "S7_95pcnt"
